### ISSUE TITLE
Match ssa.gov more closely

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#113]
The calculations are pretty accurate, but ssa.gov gives a benefit estimate assuming that the worker continues to earn the same dollar amount as the most recent year until, I think, 62.

It would be cool if the future earnings slider could be *initially* set to the same value and number of years that ssa.gov is using. This will result in the same computation until the user selects some other value.

This requires a few changes. The first is that the future dollar amount slider has as one of it's tick options the exact dollar amount that the user earned last year. Right now, it picks even values as the tick mark choices, making it impossible to select the same exact dollar amount. Second, it should be initialized to this value. Finally, the years slider should be initialized to the number of years remaining before the user turns 62.

**Comment by thadk** [comment]
Hi @Gregable and team, 
The latest enhancements and interactive visualizations on the site are fantastic and impressive. I just wanted to pop by and say hello as someone in our Code for America Brigade Network community (@andreas) identified your project as a potentially a good partnership. 
We'd somehow missed it in our earlier scoping as it didn't support Windfall Awareness Provision which was our primary use case at first for our partner.

Anyway, we've built two projects over the last few years and months:
- [SSAcalculator.org](https://ssacalculator.org) ([repo](https://github.com/codeforboston/windfall-elimination)) where we iterated to a step-by-step design, for doing some of the same tasks as ssa.tools enables, especially for state and local gov't workers.
- [AnyPIA-JS](https://github.com/codeforboston/anypia-js/) and the documentation of the text utility to generate its input: https://github.com/codeforboston/windfall-elimination/blob/develop/src/library/pia/

As you might be aware, the AnyPIA windows app is considered [the best/most accurate calculator](https://www.bogleheads.org/wiki/User:Whaleknives/Draft_SSA_Calcs). So for the last few months we partnered with the creator of the 32-bit Mac OS X port of AnyPIA to make a wrapped emscripten version of the public source code that runs in the browser. We called it AnyPIA-JS.

Even if we don't find a way to partner on the functionality of our main calculators, we'd be happy to have more users or contributors of the AnyPIA-JS project. It could help with this issue. Check out the two sets of documentation I linked above and I'm happy to explain how we've set up the API if something is unclear. While we test, we're still outputting the AnyPIA-JS onto the Javascript console on the results page when it is the chosen calculator, so that can be a good glimpse into the API.

**Comment by Gregable** [comment]
@thadk I can see why a nice API around AnyPIA would be useful. Drop me an email: ggrothau@gmail.com rather than a back in forth in the issue thread. Happy to discuss further.
