### ISSUE TITLE
wrong explanation of Primary Insurance Amount(?)

### ISSUE THREAD

**Issue by kanreki** [Gregable/social-security-tools#206]
I'm skeptical (or maybe I should say confused) by the description of PIA. 

It's my understanding that the PIA is a one-time calculation: the amount one would receive during their first year if they started taking benefits at normal retirement age. It's true that the benefit amount increases annually based on COLA. But that adjusted amount is not generally called PIA, I believe.

It may be that I'm quibbling over semantics. But with these calculations being so confusing and complex it's worth being quite careful and precise with defining terms.

Of course I might simply be wrong or confused myself, in which case I apologize for the noise.

**Comment by Gregable** [comment]
> it's worth being quite careful and precise with defining terms.

Completely agree. If you find any references, I'm more than willing to change the text here.

> It's my understanding that the PIA is a one-time calculation: the amount one would receive during their first year if they started taking benefits at normal retirement age. It's true that the benefit amount increases annually based on COLA. But that adjusted amount is not generally called PIA, I believe.

I'm uncertain, but I believe PIA does change over time. I believe what you are thinking of is the "year of eligibility". This is the year a worker attains age 62. It is at this point that the bend points in the AIME->PIA formula become fixed. "determined" may be better word than "fixed" since it's just an estimate before that point. It also is the point at which the Indexing Multiplier for taxed earnings is determined/fixed.

There is also another case you didn't mention, which is if the worker has additional years of taxable wages after the year of eligibility. These also can increase the PIA in some cases.

[This](https://www.ssa.gov/oact/progdata/retirebenefit2.html) seems to support the choice of language:

> The worker in case B is first eligible in 2019 (the year case B reached age 62). Thus the case-B PIA is the case B amount computed above truncated to the next lower dime and increased by cost-of-living adjustments, or COLAs, for 2019 through 2022. These [COLAs](https://www.ssa.gov/oact/COLA/colaseries.html) are 1.6 percent, 1.3 percent, 5.9 percent, 8.7 percent, respectively. The resulting PIA is $3,627.10.

Please let me know if you find anything different though.

**Comment by Gregable** [comment]
Interestingly the same document later has this text:

> We assume the worker in case A begins receiving benefits at the earliest possible age, which is age 62. Because case A's normal retirement age is 67 years, the benefit amount for case A is reduced for 60 months of [early retirement](https://www.ssa.gov/oact/quickcalc/early_late.html). The $2,263.30 PIA is thus reduced to a monthly benefit of $1,584.00.

This seems to be worded carefully to indicate that early/delayed reduction/increase does not change the PIA, that only affects the _benefit_. While COLA does affect PIA. The careful wording makes it seem more likely that this was intentionally worded as such.

**Comment by kanreki** [comment]
You must be right. I surely was a bit confused.

I didn't find anything on ssa.gov that made it 100% clear to me. But I did find [this page on obliviousinvestor.com](https://obliviousinvestor.com/how-social-security-benefits-are-calculated/) (I'm sure you must be familiar with Mike Piper).

Your point about additional years of wages after FRA is particularly convincing. They can easily be among the top 35 years, and must therefore affect PIA. And I suppose that could conceivably go on indefinitely, even long past age 70.
