### ISSUE TITLE
"Top 35 value" display is incorrect when using the slider to display additional years of earnings

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#32]
I entered as set of 20 years of earnings. Then I used the slider to say I had 30 more. Even when those additional earnings were set as zero, they had the "top 35" label, when clearly they were not.

However, as I increased the slider for the future earnings amount the "top 35 label" was correctly removed from the "lower" set of entered earnings.

**Comment by Gregable** [comment]
Well, technically if you only have 20 years of non-zero earnings, a $0 earnings year is in your top 35. However, I agree that this is confusing. I both fixed the computation to exclude $0 earnings in the future (this was done for the past already), but then I also realized there is no need for the slider to support a $0 value, so I set it's minimum at $1,000.

**Comment by stkeros** [comment]
I think perhaps what is happened is that if an earning is TIED for the top 35, it gets the label? Because I can currently make it display "top 35" for more than 35 years. For example, 5 years of earnings at baseline, then 35 years of future earnings less than the baseline 5 results in "top 35" showing up in 40 positions.

But only including some of the ties in the logic for displaying a label might be tricky to code (at least for me it would be!).

**Comment by Gregable** [comment]
This is true. I was aware that ties for the 'bottom top 35' would theoretically cause the labels to be incorrect, but I didn't think that was likely to happen since I'm calculating indexed earnings out to 2 decimal places. There is a [TODO](https://github.com/Gregable/social-security-tools/blob/master/src/tax-engine.js#L182) in the code to fix this. The good news is that the calculations are otherwise correct.

I wasn't thinking of the future earnings slider though. The indexed values there are all guaranteed to be the same, so this makes it much more likely to happen.

Good catch, as always! I'll work on this.
