### ISSUE TITLE
Improved readability suggestions

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#66]
The design of the main output page is a little hard to read, in my opinion. I'm referring specifically that there is not a clear way for one to understand what they are "going to be" reading.

In the about page there is "From that data, the site produces a detailed social security report."

And then the output is one linear web page which walks one through all the details of the specific amount/explanations etc. As my wife asked "what am I supposed to be looking at". I explained it's like book written just for you, explaining social security based on your actual numbers. "Oh, So I have to read everything from top to bottom?

Perhaps consider a tab, page, or section which summarizes the inputs and outputs a little more fully than the 'about' page?

Inputs required: Your actual data from ssa.gov, date of birth, and spouses PIA and DOB if married.

Here is an example of the type of text you might consider somewhere before the main output text.

> Outputs: This will generate a personal report based on your individual situation. It will walk you through the following sections: 1) How your PIA was calculated 2) Show your normal retirement age, and the effects of filing at other ages 3) If married, describes and calculates the spousal benefits which might apply. Finally, there is a graphical output where you can adjust your and/or spouses filing dates and instantly see how your personal and spousal benefits are affected.

The other thing that's awkward is that the spousal inputs "interrupts" the output.  Consider asking for this information earlier so that all the input sections are together.

**Comment by stkeros** [comment]
> The other thing that's awkward is that the spousal inputs "interrupts" the output. Consider asking for this information earlier so that all the input sections are together.

I'm modifying my suggestion here. I was relying on the demo section, where it seems that it defaults to a "married" situation. But the actual tool defaults to not married. So that's ok. That section would only expand after the user went through their own PIA calculation, which makes sense.

**Comment by Gregable** [comment]
I'll change the default for spouse to "Not Married" on the demos before out of beta, I just figured it was too much clicking to do for testing things out.

My thought was that this should be something you can print out when you are done changing things. Hence the one-page flow. Useful for a financial planner to use and give as a handout, for example.

What do you think about adding a navigation section like that seen at [link](https://getbootstrap.com/2.3.2/components.html). As you scroll, the section that you are currently viewing gets highlighted.

I'm worried about asking for too much information up front as the user may be scared off by inputting all of this stuff. Especially considering that the casual user might not know their spouse's PIA / earnings record, so asking for that early might discourage usage.

I like your thoughts though. What if the earnings input page mentioned that we will also ask for DOB and that it will give you the option to enter your spouse's information later in the report, rather than the about page?

I also want to have the spousal DOB section collapse after you've selected a date. The user should be able to uncollapse it as well, but it takes up too much space currently. I wanted to avoid drop downs which are tedious, but the consequence was a lot of visual space consumed.

Lastly, I'm not too happy about the "use this tool twice to compute PIA for you and your spouse, then enter spousal PIA here". The tool should also let you enter a spousal earning record and show you that calculation in the same document.

All good thoughts.

**Comment by stkeros** [comment]
> What do you think about adding a navigation section like that seen at link. As you scroll, the section that you are currently viewing gets highlighted.

I think Nav bars might work to reduce scrolling and break things up into chunks. Perhaps you could have a tab for "PIA explanation" "Bend Points and Chart" "Spousal information" and "Full Report", or something like that. The full report could the the printable page?

> I'm worried about asking for too much information up front as the user may be scared off by inputting all of this stuff. Especially considering that the casual user might not know their spouse's PIA / earnings record, so asking for that early might discourage usage.

One way to get around this is to have two input methods 1) direct from earnings history 2) enter in the PIA. You can then let the user select the method for self and/or spouse? For example, if I want to return to the site to play with filing dates I don't necessarily want to have to re-paste my earnings history each time. For example, for first time visitors, you just ask for self and spouse DOB, and then both sets of data can be copied: "paste your info here" (verify info), "if you have a spouse, paste spouse info here, or hit 'no spouse' to continue".  But then perhaps a button which is "I already know my/spouse future PIA and I'd like to enter it directly"?

> I also want to have the spousal DOB section collapse after you've selected a date. The user should be able to uncollapse it as well, but it takes up too much space currently. I wanted to avoid drop downs which are tedious, but the consequence was a lot of visual space consumed.

Maybe after month/year is select, there is a popup confirmation of the DOB, which if they hit yes will delete/collapse that section from view.

> Lastly, I'm not too happy about the "use this tool twice to compute PIA for you and your spouse, then enter spousal PIA here". The tool should also let you enter a spousal earning record and show you that calculation in the same document.

Agreed as above.

**Comment by Gregable** [comment]
I added the section navbar thing. It will disappear if your screen is too narrow (<1120 px wide), so if you aren't seeing it, first make sure to hard refresh and then check if you have a small screen width.
