### ISSUE TITLE
If user pastes data which includes 2018, 2018 is listed in both the "earnings record" and additional years list.

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#91]
Pasting 2019 and future years seems to be ignored however.

**Comment by Gregable** [comment]
What should it do here?

Correct me if you think I'm wrong, but if pasting from ssa.gov, you will never have an earnings record for the current year. Taxes must be filed in the following year to report earnings for the current year. In fact, you may not even have earnings for the previous year in ssa.gov yet, which can be true until very late in the year for folks who file taxes with an extension to october.

I assume the only case where someone would be doing this would be if a `txt` file were being manufactured for input by hand. In this case, I suppose we should allow the user to input any number of years, even including future years.

The "future years" slider should then start at the greater of:
 - the current year - 1   (in case earnings haven't been reported yet)
 - the latest year in the input + 1.

Does that sound reasonable?

**Comment by stkeros** [comment]
Yes, I was referring to a case where one created their own data to paste and perhaps entered a estimated 2018 amount (or future amounts). That's what I did, trying to break things. And yes, your solution is reasonable with respect to future years and the slider.

It would allow people to enter future years earnings, and evaluate "what if" scenarios. But what if people enter earnings which are later than age 62? I don't think your code would take that into account, currently?

**Comment by cfcohen** [comment]
I encountered the same problem while attempting to report 2019 earnings.  Mostly importantly this bug should not introduce confusion by creating duplicate years.  I agree that being able to enter anticipated future earnings would be a nice feature, especially in unusual circumstances where the person had several semi-retired years, or other uneven earnings where the future earnings slider wasn't getting the job done.

**Comment by Gregable** [comment]
Just so I understand the context, @cfcohen Were you manually editing your copy/paste data, or is ssa.gov giving you a 2019 earnings record while still in 2019?

**Comment by cfcohen** [comment]
Sorry for the delay in responding.  I was manually entering data, potentially including specific future earning years to evalute the impact of wage changes on the benefit amount.

**Comment by Gregable** [comment]
For the current year, entering data seems quite reasonable and should work fine.

For future years, there are a few guesses we'll need to make. Imagine for example someone enters $1M for 2021 and it's currently still 2019. We know that the maximum earnings in 2020 allowed to count towards social security is $137,700. We don't know the cap for 2021, but we can guess that it's unlikely to be above $1M. I think the only reasonable options are to apply the same cap as the latest year (2020) or to assume that the user is aware of the cap and has adjusted the input accordingly. Same for $ per credit calculations and the annual indexing factor.

I'm leaning towards applying the 2020 limits and calculations to the 2021 input in this scenario, but could be convinced otherwise. The risk, especially with the cap, is that the user is unaware of how this works and doesn't adjust their input accordingly. If so, they may get an estimate that is very far off from what they expect.

**Comment by Gregable** [comment]
Implemented as described. Let me know if you find any issues.

**Comment by cfcohen** [comment]
Ah... Good point about the growth of the maximum earnings cap.  I hadn't fully thought through the implications in your code. The correct thing to do is to make estimates of the national wage index and then calculate the benefit base from that as required by law (see [here](https://www.ssa.gov/oact/COLA/cbbdet.html)).  This but this also changes the bend points, the inflation base for the AIME, etc. so it's get complicated pretty fast.   The ANYPIA program can use one of three sets of assumptions from the latest SSA trustees report.  Everything is defined by law except the national average wage index and CPI (inflation for COLAs).
